name: 📦 Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  typecheck:
    uses: ./.github/workflows/typecheck.yml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'apps/backend/**'
            frontend:
              - 'apps/frontend/**'

  preview-backend:
    needs: [lint, typecheck, test, changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/preview.yml
    with:
      working-directory: apps/backend
    secrets: inherit

  preview-frontend:
    needs: [lint, typecheck, test, changes]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/preview.yml
    with:
      working-directory: apps/frontend
    secrets: inherit
